/**
 * Declare any constants that generated by Electrux here.
 */

declare global {
	const ELECTRUX_ENV: string | 'development';
	const ELECTRUX_DEV_URL: string;
	const ELECTRUX_PROD_URL: string;
	const ELECTRUX_WINDOW_ENTRY: string | undefined;
	const ELECTRUX_PRELOADS: Record<string, string>;
}

export { };